spring:
  application:
    name: suncode-remote-server
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /remote-server

suncode:
  remote:
    desktop-pairing-code: 123456
