[package]
name = "suncode-sdk-c"
version = "0.1.0"
edition = "2021"

[lib]
name = "suncode_agent"
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
suncode-sdk = { path = "../rust" }
suncode-common = { path = "../../agent/crates/common" }
