[package]
name = "suncode-computer"
version = "0.1.0"
edition = "2021"

[lib]
name = "suncode_computer"
path = "src/lib.rs"

[dependencies]
enigo = { git = "https://github.com/costanzo/enigo.git", rev = "36c08bbe4a00150d2b1817553985a2c115169e3a" }
image = { version = "0.25", default-features = false, features = ["png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
