<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>
    <groupId>ai.suncode</groupId>
    <artifactId>suncode-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>suncode-common</module>
        <module>suncode-config</module>
        <module>suncode-service</module>
        <module>suncode-web</module>
        <module>suncode-message</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
        <jackson.version>2.17.2</jackson.version>
        <maven-surefire-version>3.3.0</maven-surefire-version>
        <logback.version>1.5.6</logback.version>
        <mysql.version>8.3.0</mysql.version>
        <lombok.version>1.18.48</lombok.version>
    </properties>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ai.suncode</groupId>
                <artifactId>suncode-message</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.suncode</groupId>
                <artifactId>suncode-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.suncode</groupId>
                <artifactId>suncode-config</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.suncode</groupId>
                <artifactId>suncode-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>compile</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <source>17</source>
                        <target>17</target>
                        <encoding>UTF-8</encoding>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>